### ISSUE TITLE
Evaluate Potential Issue With Aggregation

### ISSUE THREAD

**Issue by gcalex5** [inclind/inclind_gutenberg_blocks#6]
While working on the updates I noticed that with AdvAgg and Aggregated JS files it was failing to find the Drupal global variable. We should investigate this and ensure that with the default settings of AdvAgg and aggregated JS/CSS files enabled that the custom blocks load without issue.

**Comment by shauntyndall** [comment]
I don't believe this is an issue as we've worked to improve our performance configuration with Critical CSS, AdvAgg and Gutenberg.
